### ISSUE TITLE
Support type: "skip" for a group of checks

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/bench-common#107]
Similar to [this issue in kube-bench](https://github.com/aquasecurity/kube-bench/issues/649)

At the moment the user can skip an individual check by setting it's type field to "skip". We could extend this support to the group level so that it's easy to skip a whole group of tests.

**Comment by yoavrotems** [comment]
Solved in https://github.com/aquasecurity/bench-common/pull/109
