### ISSUE TITLE
Scope of this tool

### ISSUE THREAD

**Issue by sambanks** [aquasecurity/bench-common#11]
Hi There

I am interested in using your kube-bench and docker-bench tools. Will this replace them as a unified tool? If so would you accept pr's for other scans? I'm currently using openscap for redhat, so it would make sense to migrate that, if that is indeed what this is for :)

Cheers
Sam

**Comment by ttousai** [comment]
Hello @sambanks 

Thanks for checking out our tools! Bench-common is not meant to be a unified tool. It is a  repository of shared code for both docker-bench and kube-bench.

We welcome and accept PRs for all our tools!

> I'm currently using openscap for redhat, so it would make sense to migrate that, if that is indeed what this is for :)

I didn't really understand this part, do you mind clarifying please?

**Comment by sambanks** [comment]
Ok thanks for the information @ttousai !

Openscap tests a local redhat instance against the cis benchmark, similar to what docker-bench and kube-bench do. I was thinking it might be worth making something like a rhel-bench for simplicity if it wasn't too much work.
