### ISSUE TITLE
Not scored checks

### ISSUE THREAD

**Issue by yoavAqua** [aquasecurity/bench-common#15]
In case a test that is "not scored" is failing, then we need to mark the result as "warning".
Currently there are cases where result is not warning for tests that are not scored.

This issue was created by jerbia in the project docker-bench, moved it to here.

**Comment by lizrice** [comment]
If a test has `type: skip` this means the user wants to skip the test. The output for this test should be marked [INFO] 

If a test has `type: manual` this means the user has to run the test manually. The output for this test should be marked [WARN] to highlight that the user needs to run the test. 

Tests may also need to be run manually if they are not scored. If there is no type, and the test has `scored: false`, the output for this test should also be marked [WARN].
