### ISSUE TITLE
Add multi-test capability

### ISSUE THREAD

**Issue by ttousai** [aquasecurity/bench-common#4]
For now we only have support for multi-test items. Some checks require multi-test support. For example Docker Bench v1.1.0 check 15.14.

**Comment by yoavAqua** [comment]
What's check 15.14?

**Comment by ttousai** [comment]
Hello @yoavAqua that was a typo. 15.14 should read `5.14`.
Nice catch.

**Comment by yoavAqua** [comment]
So I'm going to fix this issue, the only problem I see in the solution, is when will the engine know to check for multiple values, and when for single?
Should there be a special attribute in the yaml file that specify "test-for-multiple-values" in each test that needs it?
@lizrice @ttousai @jerbia

**Comment by yoavAqua** [comment]
Also this problem is relevant for all tests that needs to evaluate the output as multiple results and not just one. Examples are tests:
4.1,5.4,5.5,5.9,5.10,5.11,5.12,5.13 and more
