### ISSUE TITLE
Add JSONPath Support To Access Values Using testItem.Flag as the Expression

### ISSUE THREAD

**Issue by robertojrojas** [aquasecurity/bench-common#49]
Add JSONPath support to access value(s) coming as a result of the execution of a the `audit` command or expression.
It's possible to use the `testItem.Flag` as a carrier of a JSONPath expression which can be used to parse JSON output coming from the `audit` command.

Refer to this PR for details: https://github.com/aquasecurity/kube-bench/pull/239

**Comment by lizrice** [comment]
Only kube-bench needs JSON support right now. If we need JSON support in bench-common, or if it makes sense to include it when merging the test functionality from kube-bench, this will likely get covered as part of that work anyway.
