### ISSUE TITLE
Add test ID into error

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/bench-common#5]
We have some docker-bench tests failing with an error message like this: 

error converting 3.145728e+08: strconv.Atoi: parsing "3.145728e+08": invalid syntax 

This is almost certainly being output by the toNumeric() function which then calls os.Exit() on failure. It's impossible to tell which test is failing. Let's change this so that the test ID can be logged out as well as part of this message (probably by passing back an error from toNumeric and on up the stack until we have the ID)

**Comment by dineshtripathi30** [comment]
I see now this issue, do we have any fix for this ?

**Comment by yoavAqua** [comment]
Do we really want to exit the program if a specific test fails on converting numeric? 
@lizrice @ttousai

**Comment by lizrice** [comment]
I think we just need to add diagnostics so we can see what test is failing (it may simply be a badly configured test).

**Comment by yoavAqua** [comment]
Either case, I don't see the reason to exit the program if a specific test has failed to run.

**Comment by yoavAqua** [comment]
@lizrice  I am going to add some guards around the string conversions to prevent exiting from the program.
