### ISSUE TITLE
op: eq won't catch simple int after =

### ISSUE THREAD

**Issue by yoavrotems** [aquasecurity/bench-common#53]
because of parsing issue with op: eq --> flag + `\s*=\s*"(.*)"` it doesn't catch simple int as
somevalue: 123 
but somevalue: "123"
relate to https://github.com/aquasecurity/bench-common/pull/38

**Comment by lizrice** [comment]
This would be a good issue to do with TDD: write a unit test that recreates the problem (and tests some other valid combinations of flag and value formats) and then fix the code to pass the test.

**Comment by yoavrotems** [comment]
Added in https://github.com/aquasecurity/bench-common/pull/65
Therefore I'm closing this issue
