### ISSUE TITLE
Multiple choices in constraints doesn't work fine 

### ISSUE THREAD

**Issue by yoavrotems** [aquasecurity/bench-common#56]
When have a multi chose in constrains like
> check:
          audit: "systemctl is-enabled autofs"   
          constraints: 
            platform:
            - rhel7
            - ubuntu16
            - ubuntu18
          tests:
            test_items:
            - flag: "disabled"
              set: true                        
          remediation: |
                Run one of the following commands to disable `autofs` :
                # chkconfig autofs off
                # systemctl disable autofs
                # update-rc.d autofs disable

then none of the listed platform run.
This is from the linux-bench project which inherits from here

**Comment by lizrice** [comment]
Fixed by #61
